/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.records;

import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.ChatsLinks;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatsLinksRecord extends UpdatableRecordImpl<ChatsLinksRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK_TRACKER_DB.CHATS_LINKS.ID_CHAT</code>.
     */
    public void setIdChat(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK_TRACKER_DB.CHATS_LINKS.ID_CHAT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getIdChat() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINK_TRACKER_DB.CHATS_LINKS.ID_LINK</code>.
     */
    public void setIdLink(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK_TRACKER_DB.CHATS_LINKS.ID_LINK</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getIdLink() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return ChatsLinks.CHATS_LINKS.ID_CHAT;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return ChatsLinks.CHATS_LINKS.ID_LINK;
    }

    @Override
    @NotNull
    public Long component1() {
        return getIdChat();
    }

    @Override
    @NotNull
    public Long component2() {
        return getIdLink();
    }

    @Override
    @NotNull
    public Long value1() {
        return getIdChat();
    }

    @Override
    @NotNull
    public Long value2() {
        return getIdLink();
    }

    @Override
    @NotNull
    public ChatsLinksRecord value1(@NotNull Long value) {
        setIdChat(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsLinksRecord value2(@NotNull Long value) {
        setIdLink(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsLinksRecord values(@NotNull Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsLinksRecord
     */
    public ChatsLinksRecord() {
        super(ChatsLinks.CHATS_LINKS);
    }

    /**
     * Create a detached, initialised ChatsLinksRecord
     */
    @ConstructorProperties({ "idChat", "idLink" })
    public ChatsLinksRecord(@NotNull Long idChat, @NotNull Long idLink) {
        super(ChatsLinks.CHATS_LINKS);

        setIdChat(idChat);
        setIdLink(idLink);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatsLinksRecord
     */
    public ChatsLinksRecord(edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.pojos.ChatsLinks value) {
        super(ChatsLinks.CHATS_LINKS);

        if (value != null) {
            setIdChat(value.getIdChat());
            setIdLink(value.getIdLink());
            resetChangedOnNotNull();
        }
    }
}
