app:
  scheduler:
    enable: true
    interval: 10000
    removeUnusedLinksInterval: 86400
    force-check-delay: 10000
  database-access-type: jpa

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  bot:
    baseUrl: http://localhost:8090
    retryPolicy: linear
    retryCount: 3
    codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  github:
    baseUrl: https://api.github.com/
    retryPolicy: linear
    retryCount: 3
    codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  stackoverflow:
    baseUrl: https://api.stackexchange.com/2.3/
    retryPolicy: linear
    retryCount: 3
    codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  queryCount: 10

