/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper_jooq.repositories.jooq.link_tracker_db;

import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.Chat;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.ChatsLinks;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.Link;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.records.ChatRecord;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.records.ChatsLinksRecord;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.records.LinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * LINK_TRACKER_DB.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] { Chat.CHAT.ID }, true);
    public static final UniqueKey<ChatsLinksRecord> CONSTRAINT_34D = Internal.createUniqueKey(ChatsLinks.CHATS_LINKS, DSL.name("CONSTRAINT_34D"), new TableField[] { ChatsLinks.CHATS_LINKS.ID_CHAT, ChatsLinks.CHATS_LINKS.ID_LINK }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] { Link.LINK.URL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatsLinksRecord, ChatRecord> CONSTRAINT_3 = Internal.createForeignKey(ChatsLinks.CHATS_LINKS, DSL.name("CONSTRAINT_3"), new TableField[] { ChatsLinks.CHATS_LINKS.ID_CHAT }, Keys.CONSTRAINT_1, new TableField[] { Chat.CHAT.ID }, true);
    public static final ForeignKey<ChatsLinksRecord, LinkRecord> CONSTRAINT_34 = Internal.createForeignKey(ChatsLinks.CHATS_LINKS, DSL.name("CONSTRAINT_34"), new TableField[] { ChatsLinks.CHATS_LINKS.ID_LINK }, Keys.CONSTRAINT_2, new TableField[] { Link.LINK.ID }, true);
}
