/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper_jooq.repositories.jooq.link_tracker_db;

import edu.java.scrapper_jooq.repositories.jooq.DefaultCatalog;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.Chat;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.ChatsLinks;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.Link;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkTrackerDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINK_TRACKER_DB</code>
     */
    public static final LinkTrackerDb LINK_TRACKER_DB = new LinkTrackerDb();

    /**
     * The table <code>LINK_TRACKER_DB.CHAT</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>LINK_TRACKER_DB.CHATS_LINKS</code>.
     */
    public final ChatsLinks CHATS_LINKS = ChatsLinks.CHATS_LINKS;

    /**
     * The table <code>LINK_TRACKER_DB.LINK</code>.
     */
    public final Link LINK = Link.LINK;

    /**
     * No further instances allowed
     */
    private LinkTrackerDb() {
        super("LINK_TRACKER_DB", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chat.CHAT,
            ChatsLinks.CHATS_LINKS,
            Link.LINK
        );
    }
}
