/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper_jooq.repositories.jooq.link_tracker_db;

import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.Chat;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.ChatsLinks;
import edu.java.scrapper_jooq.repositories.jooq.link_tracker_db.tables.Link;
import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in LINK_TRACKER_DB.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>LINK_TRACKER_DB.CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>LINK_TRACKER_DB.CHATS_LINKS</code>.
     */
    public static final ChatsLinks CHATS_LINKS = ChatsLinks.CHATS_LINKS;

    /**
     * The table <code>LINK_TRACKER_DB.LINK</code>.
     */
    public static final Link LINK = Link.LINK;
}
