app:
  telegram-token: ${TELEGRAM_TOKEN}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: botMessages
      mappings: edu.java.scrapper.api.models.requests.LinkUpdateRequest:edu.java.bot.api.models.requests.LinkUpdateRequest
    topicName: botUpdates
    badResponseTopicName: botUpdates_dlq

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    baseUrl: http://localhost:8080
    retryPolicy: linear
    retryCount: 3
    codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  queryCount: 10

